services:
  keycloak-db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - keycloak-db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 1G

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
      ldap:
        condition: service_healthy
    networks:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
          pids: 200
        reservations:
          cpus: '1.0'
          memory: 2G

  flask-app:
    build: ./app
    ports:
      - "15000:5000"
    networks:
      - frontend
    read_only: true
    security_opt:
      - no-new-privileges
    depends_on:
      keycloak:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
          pids: 100
        reservations:
          cpus: '0.25'
          memory: 256M

  ldap:
    image: osixia/openldap:1.5.0
    env_file:
      - ./.env
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - backend
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost:389 -b '' -s base '(objectclass=*)' > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
          pids: 100
        reservations:
          cpus: '0.25'
          memory: 256M

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    env_file:
      - ./.env
    ports:
      - "8081:80"
    depends_on:
      - ldap
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
          pids: 100
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  keycloak-db_data:
  ldap_data:
  ldap_config:

networks:
  frontend:
  backend:
